name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_ANNONCE }}
          username: ${{ secrets.SSH_USER_ANNONCE }}
          key: ${{ secrets.SSH_PRIVATE_KEY_ANNONCE }}
          port: ${{ secrets.SSH_PORT_ANNONCE }}
          script: |
            set -e
            cd /var/www
            if [ ! -d "annonce" ]; then
              git clone https://github.com/hamedor/annonce-landing.git annonce
            fi
            cd annonce
            npm install
            npm run build
            pm2 reload annonce || pm2 start npm --name annonce -- run preview
            pm2 save